version: '2.1'

services:

  proxy:
     build:
       context: ../../proxy
     container_name: proxy
     environment:
       - DNS_TCP_ADDR=127.0.0.11
       - DNS_TCP_PORT=53
     ports:
       - "9000:9000" 
     networks:
       - sandbox

#  cassandra:
#    image: cassandra:2.1
#    container_name: cassandra
#    networks:
#      - sandbox

  cassandra:
    image: gcr.io/google-samples/cassandra:v12
    container_name: cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=sandbox
      - CASSANDRA_DC=dc-sandbox
      - CASSANDRA_RACK=rack-sandbox
      - CASSANDRA_AUTO_BOOTSRAP=false
    networks:
      - sandbox

  locator:
    image: consul:0.8.3
    container_name: locator
    ports:
      - "8500:8500"
    networks:
      - sandbox

  activityservice:
    image: chirper/activity-stream-impl
    container_name: activityservice
#    ports:
#      - "9000:9000"
#      - "2551:2551"
    environment:
      - APPLICATION_SECRET=fish
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - ACTIVITYSERVICE_BIND_PORT=9000
      - ACTIVITYSERVICE_BIND_IP=0.0.0.0
      - AKKA_REMOTING_PORT=2551
      - AKKA_REMOTING_BIND_PORT=2551
      - AKKA_REMOTING_HOST=activityservice
      - AKKA_SEED_NODES=activityservice:2551
      - CONSUL=locator
    networks:
      - sandbox      
   
  chirpservice:
    image: chirper/chirp-impl
    container_name: chirpservice
#    ports:
#      - "9000:9000"
#      - "2551:2551"
    environment:
      - APPLICATION_SECRET=fish
      - CASSANDRA_SERVICE_NAME=cassandra
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CHIRPSERVICE_BIND_PORT=9000
      - CHIRPSERVICE_BIND_IP=0.0.0.0
      - AKKA_REMOTING_PORT=2551
      - AKKA_REMOTING_BIND_PORT=2551
      - AKKA_REMOTING_HOST=chirpservice
      - AKKA_SEED_NODES=chirpservice:2551
      - CONSUL=locator
    networks:
      - sandbox      
       
  friendservice:
    image: chirper/friend-impl
    container_name: friend_service
#    ports:
#      - "9000:9000"
#      - "2551:2551"
    environment:
      - APPLICATION_SECRET=fish
      - CASSANDRA_SERVICE_NAME=cassandra
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - FRIENDSERVICE_BIND_PORT=9000
      - FRIENDSERVICE_BIND_IP=0.0.0.0
      - AKKA_REMOTING_PORT=2551
      - AKKA_REMOTING_BIND_PORT=2551      
      - AKKA_REMOTING_HOST=friendservice
      - AKKA_SEED_NODES=friendservice:2551
    networks:
      - sandbox
      
  web:
    image: chirper/front-end
    container_name: web
#    ports:
#      - "9000:9000"
    environment:
      - APPLICATION_SECRET=fish
      - WEB_BIND_PORT=9000
      - WEB_BIND_IP=0.0.0.0  
    networks:
      - sandbox
  
networks:
  sandbox:  
